version: '3'
services:
  nginx-server:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - my-network
    depends_on:
      - cidades-service-1
      - cidades-service-2

  cidades-service-1:
    build: ../cidades-services/spring/
    image: alisson/cidades-service-1
    container_name: cidades-service-1
    networks:
      - my-network
    ports:
      - 8081:8080
      
  cidades-service-2:
    build: ../cidades-services/spring/
    image: alisson/cidades-service-2
    container_name: cidades-service-2
    networks:
      - my-network
    ports:
      - 8082:8080

networks:
  my-network:
    driver: bridge